include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.mocks.dart"

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    require_trailing_commas: true
