name: software
description: An Ubuntu software app made with Flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_localizations:
    sdk: flutter
  handy_window: ^0.1.4
  image: ^3.1.3
  palette_generator: ^0.3.3
  provider: ^6.0.2
  safe_change_notifier: ^0.1.0+1
  snapd:
    git: https://github.com/canonical/snapd.dart
  ubuntu_service: ^0.1.0
  url_launcher: ^6.1.2
  yaru: ^0.3.2
  yaru_colors: ^0.1.0
  yaru_icons:
    git: https://github.com/ubuntu/yaru_icons.dart
  yaru_widgets:
    git: https://github.com/ubuntu/yaru_widgets.dart

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
