name: snap-store
summary: App Center
description: App Center
confinement: strict
base: core22
grade: stable
version: git

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-tag: 3.10.6
    source-depth: 1
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      ln -s $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter/bin/dart $SNAPCRAFT_PART_INSTALL/usr/bin/dart
      $CRAFT_PART_INSTALL/usr/bin/flutter doctor
    build-packages:
      - clang
      - cmake
      - curl
      - libgtk-3-dev
      - ninja-build
      - unzip
      - xz-utils
      - zip
    override-prime: ''

  snap-store:
    after: [flutter-git]
    source: .
    plugin: nil
    override-build: |
      # work around pub get stack overflow # https://github.com/dart-lang/sdk/issues/51068#issuecomment-1396588253
      set +e
      dart pub get
      set -eux
      flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/

apps:
  snap-store:
    command: bin/snap-store
    desktop: bin/data/flutter_assets/assets/app-center.desktop
    extensions: [gnome]
    plugs:
      - appstream-metadata
      - desktop
      - desktop-launch
      - network
      - snapd-control
      - packagekit-control

slots:
  packagekit-svc:
    interface: dbus
    bus: session
    name: org.freedesktop.PackageKit
  dbus-name:
    interface: dbus
    bus: session
    name: io.snapcraft.Store
