name: flutter build linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: build linux binary
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: sudo apt -y install git curl cmake ninja-build make clang libgtk-3-dev pkg-config && mkdir -p ~/development && cd ~/development && git clone https://github.com/flutter/flutter.git -b stable && echo 'export PATH="$PATH:$HOME/development/flutter/bin"' >> ~/.bashrc && source ~/.bashrc
      - run: flutter build linux -v
