name: cla-check
on:
  pull_request:
    branches: [main]

jobs:
  cla-check:
    if: contains(fromJson('["weblate",), github.event.pull_request.user.login) == false
    runs-on: ubuntu-20.04
    steps:
      - name: Check if CLA signed
        uses: canonical/has-signed-canonical-cla@v1
