name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: flutter test --coverage
      - uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}

  integration:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: sudo apt update
      - run: sudo apt install -y clang cmake libblkid-dev libglib2.0-dev libgtk-3-dev liblzma-dev network-manager ninja-build packagekit pkg-config xmlstarlet xvfb
      - run: |
          # See https://github.com/cockpit-project/cockpit/issues/8477
          sudo touch /etc/NetworkManager/conf.d/10-globally-managed-devices.conf
          sudo systemctl restart NetworkManager.service
      - run: |
          actionFile="/usr/share/polkit-1/actions/org.freedesktop.packagekit.policy"
          installAction="org.freedesktop.packagekit.package-install-untrusted"
          sudo xmlstarlet ed -L -u "//action[@id='$installAction']/defaults/allow_active" -v yes $actionFile
          removeAction="org.freedesktop.packagekit.package-remove"
          sudo xmlstarlet ed -L -u "//action[@id='$installAction']/defaults/allow_active" -v yes $actionFile
      - run: xvfb-run -a -s '-screen 0 1024x768x24 +extension GLX' flutter test integration_test