name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: flutter test --coverage
      - uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: sudo apt update
      - run: sudo apt install -y xmlstarlet xvfb
      - run: |
          actionFile="/usr/share/polkit-1/actions/org.freedesktop.packagekit.policy"
          installAction="org.freedesktop.packagekit.package-install-untrusted"
          sudo xmlstarlet ed -L -u "//action[@id='$installAction']/defaults/allow_active" -v yes $actionFile
          removeAction="org.freedesktop.packagekit.package-remove"
          sudo xmlstarlet ed -L -u "//action[@id='$installAction']/defaults/allow_active" -v yes $actionFile
      - run: xvfb-run -a -s '-screen 0 1024x768x24 +extension GLX' flutter test integration_test